shorts = {
    'г.': 'grams',
    'г': 'grams',
    'грамм': 'grams',
    'граммов': 'grams',
    'мл.': 'milliliters',
    'мл': 'milliliters',
    'миллилитр': 'milliliters',
    'ст.л': 'tablespoon',
    'ст.л.': 'tablespoon',
    'ст.': 'tablespoon',
    'столовая ложка': 'tablespoon',
    'столовых ложек': 'tablespoon',
    'стол': 'tablespoon',
    'ч.': 'teaspoon',
    'чай': 'teaspoon',
    'штука': 'piece',
    'шт': 'piece',
    'шт.': 'piece',
    'головка': 'piece',
    'зубчик': 'slice',
    'зуб': 'slice',
    'долька': 'slice',
    'долек': 'slice',
    'дольки': 'slice',
    'стакан': 'glass',
    'стак': 'glass',
    'стак.': 'glass',
    'стакана': 'glass',
    'щеп': 'pinch',
    'вкусу': 'grams',
    'желанию': 'grams'
}
